docs/configuration/nerd-fonts.md
Current curl download link return `curl: (22) The requested URL returned error: 404`, replaced with a working one
=> replacing not working curl download link

docs/plugins/plugin-quickstart.md
`cmd="Rnvimr"` no longer works, changed to RnvimrToggle fixes
`vim.g.rvimr_ex_enable = 1` no longer works, since netrw is disabled by lvim default
`require("lv-rnvimr").config()` makes rnvimr throws err
remove set key maps, key map shouldn't be buried in packer config, it's hard for user to see, if they just copied and pasted, they will have no idea how did the key get set up.
=> Rnvimr plugin quick start doesn't work(3 errs)

docs/plugins/plugin-quickstart.md
Using the current setup may lead to some from lazy loading setup, tabnine started before compe sometimes messes up things.
https://www.reddit.com/r/neovim/comments/ohokze/how_to_install_tabnine_with_nvimcompe/
=> Potential not working tabnine-compe setup

docs/plugins/02-available-plugins.md
Use both of these settings blows my lvim, I have read the documentation from lsp_signature which stated use either 1 option not both
=> Remove confusing part

docs/languages/javascript.md, docs/languages/typescript.md, docs/languages/vue.md
Add a bit of information to JavaScript, TypeScript and Vue. Also the config samples have been simplified by removing the obsolete `args` property.
=> [Refactor] JavaScript, TypeScript, and Vue

docs/languages/c_cpp.md
Simplify c/c++ configuration by removing the `args` properties. 
Fix clangd_format typo to clang_format. 
Add mention on config file.
=> [Refactor] c/c++ simplified and fixed

docs/languages/README.md, docs/languages/python.md
Remove empty args from linter and formatter config examples. Add mention of `:LvimInfo`.
=> [Bugfix] Remove empty args from linter and formatter config examples

docs/configuration/02-keybindings.md
Seems to be just `leader` now: https://github.com/LunarVim/LunarVim/blob/rolling/lua/keymappings.lua#L178
=> Update option to set leader

docs/configuration/01-settings.md
Hello! 
I fixed a very small typo in the Example options section.
=> fix: typo on titlestring command

docs/02-after-install.md
why:
currently it is a bit unclear (at least to me, that formatting is not supported out of the box.)
what:
At least in the quick start we explain or give a hint that this might need configuration / installation outside of Lunarvim
See:
https://github.com/LunarVim/LunarVim/issues/1600
=> doc: formatting and linting for quick start

docs/configuration/01-settings.md
This line doesn't work:
```lua
vim.opt.undodir = CACHE_PATH .. "/undo" -- set an undo directory
``` 
Through testing I could only make it work in this way (example):
```lua
vim.opt.undodir = ".cache/nvim/undo"
```
I'm proposing this change but please feel free to suggest a better way.
Thank you!
=> Fixes undodir definition

docs/languages/qml.md
null-ls [recently added support](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/304) for a couple of QML tools, so I thought it is worth to add a list here.
=> feat: add docs for QML

docs/languages/go.md
Hi there!
The way  DAPInstall configures [dap for the Go language](https://github.com/Pocco81/DAPInstall.nvim/blob/main/lua/dap-install/core/debuggers/go_delve.lua) , it's by using [this configuration](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#go-using-delve-directly) from the `nvim-dap` package. As stated in the same paragraph (from the last link), this is an `experimental` way from delve to implement the `DAP` protocol directly. I've been playing around with it and it's consistently throwing errors. 
I propose to let know folks the stable way of debugging Go code by using the vs-code debugging adapter, while the other implementation gets stable enough so we can recommend it.
Thanks for this amazing configuration!
=> Add additional debug information for the Go language

docs/languages/README.md
Change `with` to `width` in formatter args example
=> Typo: formatter arg typo

docs/.vuepress/config.js, docs/.vuepress/templates/index.dev.html, docs/.vuepress/templates/index.ssr.html
screen would flash from what seems like a background transition
in the default CSS of Vuepress
index.dev and index.ssr html files added in .vuepress/templates that
are used to remove the default CSS that causes this behavior on
initial load
Solution found in this discussion [here](https://issueexplorer.com/issue/vuepress/vuepress-next/387)
=> fix: fixed screen flashing on initial load when using dark mode

docs/plugins/02-default-plugins.md
The documentation was still pointing to the now deprecated `nvim-lspinstall` plugin, but the actual plugin installed is `nvim-lsp-installer`. This updates the name in the documentation, as well as the link.
=> Update lsp installer link and name

docs/languages/rust.md
Closes #150 (if `ccppr_lldb` is actually broken)
=> Fix Rust example debug config

docs/languages/javascript.md
i noticed that `## Supported formatters` and `## Supported linters` sections have duplications at the end of page which they have the same content. so i proposed this change to remove one of them.
(LunarVim is very good! thanks for your awesome works 👍)
=> chore: remove duplications in /languages/javascript page

docs/languages/README.md
Some major changes:
1. Use `command` instead of `exe`, as it has been the de facto way to set up in null-ls documentation
2. Show how to register code-actions
3. Show how to register linter/formatter/code-actions using name, not command 
4. Unify the configuration documentation under one heading level
=> Update documentation about null-ls settings

docs/languages/README.md
This PR ams to make easier for those wanting to fine-tune their null-ls configs by reducing the gap between official docs and lunar-vim methodology.
=> Trying to reduce the black magic around null-ls

docs/plugins/02-extra-plugins.md
nvim-ts-autotag > nvim-treesitter-context
=> docs: fix wrong plugin name

docs/01-installing.md
* In the official documentation it says that you need `Neovim 0.6.1` while in the installation it depends on `Neovim v0.7`
=> Update Neovim Version

docs/plugins/02-extra-plugins.md
Because it took me a while to figure out how to enable this via `config.lua`.
=> add instructions for enabling rainbow mode

docs/01-installing.md
I encountered this error while installing.
Solved it by installing `gnumake`.
```
Cloning LunarVim configuration
Cloning into '/home/miki/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 150 (delta 5), reused 67 (delta 4), pack-reused 0
Receiving objects: 100% (150/150), 117.67 KiB | 3.27 MiB/s, done.
Resolving deltas: 100% (5/5), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
/dev/fd/63: line 388: make: command not found
```
=> Add make prequisite

docs/configuration/04-nerd-fonts.md
There is a small typo on the Nerd Fonts instructions.
=> Fix typo in Nerd Fonts > Manual Installation

docs/plugins/02-extra-plugins.md
This commit modifies the copilot-cmp example setup. It moves copilot completions to the top of the list and adds the source name "Copilot" such that the completion is easily identified.
=> Improvement for copilot-cmp setup

docs/plugins/02-extra-plugins.md
Update the docs to match current project [README](https://github.com/LunarVim/LunarVim/blob/rolling/README.md?plain=1#L122) (which works).
Docs always list `event` key first, README doesn't. :)
=> fix(lsp_signature): Correct setup instructions

docs/configuration/08-custom-snippets.md
This fix the wrong path mentioned here #203
Path to config file should be `~/.config/lvim/snpippet`
=> Fix wrong path to config file

docs/plugins/02-extra-plugins.md
This fixes the documentation example for adding plugin simrat39/symbols-outline.nvim.
The method described in the documentation fails with a lua fatal error. A related problem is described in the plugin repo as [issue #156](https://github.com/simrat39/symbols-outline.nvim/issues/156#issuecomment-1222192595).
The fix is directly based in [this comment in the issue thread](https://github.com/simrat39/symbols-outline.nvim/issues/156#issuecomment-1222192595).
I tested the fix and it solves the problem. IMHO the documentation needs to be updated accordingly.
=> Fix instructions to add plugin simrat39/symbols-outline.nvim.

docs/languages/README.md
Fixes a typo, where "to provider" should be "to provide".
=> Fix typo in languages/README.md

docs/languages/scala.md
`lvim.autocommands.custom_groups` is deprecated as of my installation of the stable version of lvim (23 SEP 2022). In this change, I rewrote the deprecated configuration.
=> Update config.lua section

src/components/Preview/index.jsx
previously the images weren't loaded form the base path when viewing the site in another language
=> fix: preview images path in different language

.github/workflows/docs.yml, docusaurus.config.js
I think the new site is ready enough to get actually deployed to `lunarvim.org`.
Tested on my fork:
https://vonpb.github.io/lunarvim.org/
the baseUrl error should resolve on the actual custom domain...
=> feat: pages deployment

docs/01-installation.md, docs/configuration/03-colorschemes.md
Embed the two youtube videos [chris@machine](https://youtu.be/NlRxRtGpHHk) and [chris@machine](https://youtu.be/OOr1qM17Lds) from [chris@machine](https://www.youtube.com/c/ChrisAtMachine) in the docs first is embeded in installation guid and second is embeded in color schemes docs respectively.
=> docs: add tutorial to installation and color scheme section

docusaurus.config.js, package.json
This feature is important, the last documentation contains a search bar that saves a lot of time!.
Answering to #257, i think this isn't in purpose.
- Add yarn dependency of docusaurus search plugin.
- Working in build mode.
- Non tested with other languages, just english due #259 hasn't been approved.
=> feat: Enabled local search

docs/languages/README.md, docs/plugins/README.md
There are a bunch of admonitions that are not working right now. So this PR aims to fix that.
The changes were made following the [usage with prettier](https://docusaurus.io/docs/markdown-features/admonitions#usage-with-prettier) recommendations.
=> fix: all invalid admonitions

src/components/Languages/index.jsx
I could also add a sort call when generating the list, but this seemed better. Happy to do it otherwise.
=> fix: sort languages alphabetically

docs/languages/scala.md
Summary of this PR:
- Fix a bug on the previous setup which made the `metals_config.on_attach` callback not called.
- Fixed a bug about metals being initialized every time Lunarvim config is invoked, even though we're not in scala buffers. PS: This is also a current [issue.](https://github.com/LunarVim/LunarVim/issues/3340).
- Added dap capability.
=> docs: fixed scala setup and added dap capability in scala

docs/plugins/02-extra-plugins.md
Hi :wave:,
according to https://github.com/Pocco81/auto-save.nvim#-disclaimer-breaking-change the name was adjusted from `AutoSave` to `auto-save`.
Therefore this PR adjusts the URL.
=> docs: update `auto-save.nvim` plugin url

docs/configuration/02-keybindings.md
A quick addition on how to add LSP bindings.
Especially, because `lvim.lsp.buffer_mappings.normal_mode['<key>'] = false` is floating around in some issues, which doesn't work and results a Lua Exception.
=> docs: Add how to modify LSP bindings

docs/plugins/02-extra-plugins.md
Suggested configuration did not work out of the box (at least with my setup).
I simply copy/pasted the [official doc](https://github.com/pwntester/octo.nvim#-installation) to make it work.
=> doc(): fix octo plugin install

docs/01-installation.md
This adds links for the dependencies under the "Prerequisites" category of the [installation page](https://www.lunarvim.org/docs/installation)
=> docs: add links for dependencies on installation page

docs/languages/README.md
Update doc to refer to `mason` rather than `nvim-lsp-installer` as the latter is no longer used.
=> docs: refer to `mason` instead of `nvim-lsp-installer`

docusaurus.config.js
my versioning PR broke links, so the latest build failed, this PR fixes it
moves latest docs to `/docs`
`/docs/1.2` -> `/docs/`
=> fix broken links

docs/02-quick-start.md, docs/03-keybind-overview.md, docs/configuration/02-keybindings.md, versioned_docs/version-1.2/02-quick-start.md, versioned_docs/version-1.2/03-keybind-overview.md, versioned_docs/version-1.2/configuration/02-keybindings.md
adds an overview of the most commonly used mappings
fixes #297
=> docs: add keybind overview

docs/03-keybind-overview.md, docs/configuration/02-keybindings.md, versioned_docs/version-1.2/03-keybind-overview.md, versioned_docs/version-1.2/configuration/02-keybindings.md
Added few key examples, statements and fixed spelling
Leader key information must come first in the doc. User should know which key is to be pressed first.
Other key-bindings come after it. Hence shifted the info at the top.
=> docs: changes in keybind-overview and configuration/keybindings

versioned_docs/version-1.2/plugins/02-extra-plugins.md
I was soooooooo frustrated with minimap, its conflicts, and its bugs, that I seeked for an alternative for days. I finally found a GREAT ONE called mini.map :)
It works ridiculously well, it's extremley fast and lightweight, and it can double as a sidebar too! 100% Lua, no external dependencies (bar gitsigns if one wants to integrate it), and forget about wxfr brittle changes and stitches to make it compatible. it just works!!!
more rationale here: https://github.com/LunarVim/LunarVim/discussions/2838#discussioncomment-4239332
=> docs: add mini.map to extra plugins

docs/plugins/02-extra-plugins.md
Inform the user that treesitter can be enabled when using vim-matchup, similar to nvim-ts-rainbow.
=> Document vim-matchup treesitter integration enabling

docs/configuration/02-keybindings.md, versioned_docs/version-1.2/configuration/02-keybindings.md
Adds an additional example for neovim / vim newbies, such as myself, as to how to modify keybindings using lvim's native config methods.
This is a good example because:
* It is on its own a useful command, and so may appear in searches (SEO and internal search)
* Demonstrates that key maps can be assigned to keys, not just :commands, which is what I mistakingly thought when reading the lone example
=> Add example for remapping keybindings

.github/workflows/docs.yml
Run deployment CI only when repo owner is LunarVim.
=> ci(plugin): run ci only for lunarvim org

docs/01-installation.md, versioned_docs/version-1.2/01-installation.md
Separated Uninstall script for convenient copy-pasting
Previously:
```
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)
```
Two alternative scripts in the same code field defeats the purpose of copy pasting. So the two alternatives are separated into:
</br>
```
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh
```
**or**
```
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)
```
The users can now readily use the copy button provided.
=> docs: separate uninstall scripts

docs/03-keybind-overview.md
This patch adds a new Git section to the Keybind overview page it shows all default git keymaps and tips to enable lazygit
Small fixes:
- Rename file explorer section to better match the other sections capitalization/style
- Fix typo on line 31 "telesope" -> "telescope"
Fixes: #319
---
The info about enabling the builtin terminal was added because the `config_win.example.lua` used to come with it disabled before the PR [#3519](https://github.com/LunarVim/LunarVim/pull/3519#issue-1461993179) on LunarVim.
| LazyGit Tips             |  Section rename | New Git section
:-------------------------:|:-------------------------:|:------------
=> docs(keybindings): fix typo

docs/01-installation.md, versioned_docs/version-1.2/01-installation.md
=> docs(installation): fix `make` link

docusaurus.config.js, src/components/Hero/index.jsx
There was confusion in the discord about the support button: is it for supporting the user or lunarvim.
this pr adds a `Get Help` button and rewords `Support` to `Donate` to make it clearer
=> fix: clearer hero CTA buttons

src/components/MeetTheTeam/styles.modules.css
In the optimized build the images don't show because `.image--show` has lower priority than `.image`, idk why that is but this fixes it
=> fix(MeetTheTeam): css class priority

docs/configuration/appearance/colorschemes.md, docs/configuration/language-features/linting-and-formatting.md
=> docs: format_on_save autocmd pattern and overriding hlgroups

docusaurus.config.js
1.2 is not new anymore, I commented out the bar so it's easier to add it next time
=> refactor: remove "new release" announcement bar

versioned_docs/version-1.2/quick-start.md
=> docs(quick-start.md): remove trailing space

docs/configuration/plugins/example-configurations.md
ggandor is now working on leap.nvim instead of lightspeed
=> docs(example-configurations): add leap.nvim plugin example

docs/configuration/plugins/example-configurations.md, versioned_docs/version-1.2/plugins/extra-plugins.md
[CHECKLIST]
[x] I have read the [contributing guidelines](https://github.com/LunarVim/lunarvim.org/blob/master/CONTRIBUTING.md)
[x] I prefixed the title with one of the following tags:
- docs: on documentation updates
the original plugin maintainer has archived the repo and encouraged anybody to take over. the fork replacing the original here does that egregiously. installed and working on my setup.
=> docs(example-plugins): replace nvim-ts-rainbow with maintaned fork

.github/actions/spelling/expect.txt, docs/configuration/plugins/example-configurations.md, versioned_docs/version-1.2/plugins/extra-plugins.md
[CHECKLIST]
neo-tree is an amazing alternative to nvim-tree. been using it for a long while and never had issues. it also offers a wider feature set and works flawlessly. I used the stable branch in my config, as neo-tree cares about that to provide solid software.
hope this helps.
=> docs(example-plugins): adding nvim-neo-tree alternative to nvim-tree

docs/installation/installation.md
Hello everyone!
I am a long-time vanilla vim user, and curious about LunarVim :) Here is some context for this PR: While testing LunarVim I was happy to see that a Docker command was made available. Since I have PTSD from breaking stuff by installing new stuff, I dockerize a lot of things.
Once I launched it, I got frustrated because I couldn't install every suggestion and felt perplexed that the container was running as root to launch the install script. Since it's only a demo, I didn't really want it to be unnecessarily privileged on my machine.
To answer these points, I suggest the following:
- Add yarn, python3, and cargo as dependencies
- Add the lunaruser and wrap the install and run commands with `su`.
WDYT?
Cheers!
Loris
=> docs(installer): Root-less Docker installation, able to install everything

docs/installation/installation.md
Having a reference to this somewhere during installation for something that is built-in to the `<Leader>` suggestions.
Someone may not want to use or install it but having a reference for a feature that is built-in to the default installation of LunarVim is helpful.
Wording can be updated as the maintainers deem fit
=> docs(installation): Add Optional Feature Pre-reqs: lazygit

docusaurus.config.js, src/pages/index.jsx
The following is what Google Messages shows when I send lunarvim.org to a friend (notice the description):
https://docusaurus.io/docs/api/docusaurus-config#tagline
I haven't tested this yet.
=> fix(docs): Add `tagline` for Link Previews

docs/configuration/language-features/linting-and-formatting.md
Was H3 instead of H2 so was indented incorrectly on the right-hand menu.
=> Fix heading

docs/installation/installation.md
Update the documentation to reflect https://github.com/LunarVim/LunarVim/blob/91bdb7cd5131bdeeb0fd68ad58aaf69adb510983/lua/lvim/utils/git.lua#LL61C3-L61C3
Currently LunarVim doesn't switch branch to the latest release automatically.
=> docs: clarify update branch

docs/installation/post-install.md
=> Fix a typo in post-install.md

.github/actions/spelling/expect.txt, docs/beginners-guide/keybinds-overview.md, versioned_docs/version-1.3/beginners-guide/keybinds-overview.md
I noticed that on macOS using Alacritty, the Option-key doesn't work out-of-the-box as meta-key.
Although not necessarily a LunarVim (or Neovim) issue, the docs currently already include a tip to configure iTerm2 so I thought it'd be nice to also include the instructions to configure Alacritty.
=> docs: add instructions for Alacritty key setting

i18n/zh-Hans/docusaurus-plugin-content-docs/current/configuration/language-features/linting-and-formatting.md
=> docs(zh-Hans): fix typo

docs/configuration/plugins/plugins.md
=> docs: add examples to run dev mode

.github/actions/spelling/expect.txt, docs/beginners-guide/plugins-overview.md
Added plugins overview and details about core plugins to beginner's guide / plugins-overview
=> Added plugins overview and details to beginner's guide

docs/installation/installation.md
=> docs(installation): fix typo

i18n/zh-Hans/docusaurus-plugin-content-docs/current/configuration/language-features/custom-snippets.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/configuration/language-features/language-servers.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/configuration/language-features/linting-and-formatting.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/faq.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/configuration/appearance/colorschemes.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/configuration/appearance/statusline.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/configuration/keybindings.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/configuration/plugins/core-plugins.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/configuration/plugins/user-plugins.md
=> docs(zh-Hans): fix typo and sync en

docs/installation/installation.md, versioned_docs/version-1.3/installation/installation.md
Add a missing comma to the current and next version of the docs
=> docs: add missing comma

versioned_docs/version-1.3/configuration/plugins/example-configurations.md
There was an [issue](https://github.com/f-person/git-blame.nvim/issues/65) on git-blame.nvim about `vim.g.gitblame_disable = 0` not working with Lunar.
I recently implemented a setup function which solves this issue. This commit uses `setup`, instead of legacy vim.g in order to avoid any confusions for users who wanna use git-blame :).
=> docs(gitblame): Use `setup`

versioned_docs/version-1.2/installation.md
Fixing missing python3 and cargo dependencie while trying lunarvim with docker.
ex for python
-------------------------------------------------------------------------------- Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli? [y]es or [n]o (default: no) : y
[WARN]: skipping installing optional nodejs dependencies due to insufficient permissions. check how to solve it: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally -------------------------------------------------------------------------------- Would you like to install LunarVim's Python dependencies: pynvim? [y]es or [n]o (default: no) : y
Verifying that pip is available..
/dev/fd/64: line 322: python3: command not found
=> docs: Missing dependencies trying with docker

docs/installation/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/installation/installation.md, versioned_docs/version-1.2/installation.md, versioned_docs/version-1.3/installation/installation.md
Simplify the experience of trying out LunarVim in a docker container, to mitigate issues like https://github.com/LunarVim/LunarVim/issues/4372
=> docs(installation): skip dependency install when trying in docker

src/css/custom.css
In your docusaurus config you're setting the hideOnScroll of the Navbar to false so that the navbar is sticky, and apperently there is a bug in docusaurus that makes a 1px gap apear on top of the navbar in this situation on some zoom levels( like 125% in my case), so when the user scrolls the content behind the navbar could be seen through that gap, like you can see in this picture:
This behavior is well documented in this stackoverflow question: https://stackoverflow.com/questions/64729642/css-sticky-ignores-1px
The root of the problem is the combination of position sticky and top 0, the solution is to simply add a top of -1px to the navbar to compensate for the gap, it's the only thing I added as you can already see.
=> fixed navbar top gap

versioned_docs/version-1.2/plugins/extra-plugins.md
=> Update extra-plugins.md for typo

docs/configuration/language-features/language-servers.md
This update the reference to allow manual installation of lsp servers from `lvim.lsp.automatic_servers_installation` to `.installer.setup.automatic_installation`.
=> docs(fix): update reference to disable automatic installation of lsp

docs/installation/installation.md, versioned_docs/version-1.3/installation/installation.md
Updated the [Website Installation page](https://www.lunarvim.org/docs/installation) by incorporating the essential dependency, [ripgrep](https://github.com/BurntSushi/ripgrep) as it is a prerequisite for utilizing the find_file option showcased in lvim, as documented in [Telescope.nvim](https://github.com/nvim-telescope/telescope.nvim).
=> docs(docs & versioned_docs): add ripgrep dependency in prerequisites

versioned_docs/version-1.3/configuration/plugins/example-configurations.md
=> docs: Update example-configurations.md

versioned_docs/version-1.2/plugins/extra-plugins.md
the command was switched from run to build
=> chore: run replaced with build

versioned_docs/version-1.2/installation.md, versioned_docs/version-1.3/installation/installation.md
Fixed the docker run commands for the versioned-docs by adding the curl requirement. Looks like alpine doesn't include it by default anymore.
=> versioned-docs(installation): Fixed docker commands for versions 1.2 and 1.3

versioned_docs/version-1.3/configuration/plugins/example-configurations.md
Fixed docs related to `lsp_signature` plugin installation. Current live version of docs have incorrect instructions that no longer work.
Fix was taken from this [comment](https://github.com/ray-x/lsp_signature.nvim/issues/202#issuecomment-1190525409) (thanks to @FelipeLema)
=> Fixed documentation for lsp_signature plugin
