LunarVim/lunarvim.org

docs/community/01-meet-the-team.md
=> Shameless plug

docs/community/01-meet-the-team.md
=> we need the new line

docs/02-after-install.md, docs/community/01-meet-the-team.md, docs/configuration/autocommands.md, docs/configuration/colorschemes.md, docs/configuration/dap.md, docs/configuration/disable-compe.md, docs/configuration/keybindings.md, docs/configuration/transparency.md, docs/languages/enabling-a-language-server.md, docs/languages/julia.md, docs/plugins/README.md, docs/plugins/extending-configuration-for-core-plugins.md, docs/plugins/plugin-quickstart.md
Modify: autocommands, colorschemes, keybindings, plugins, extending configurations, plugin quickstart
Added sections: colorschemes, dap, language server, extending core plugins
=> Additions 2

docs/dev/README.md
I'm quite new at this, so if you find that things are missing, please leave me a comment.
=> Define documentation for developers

docs/.vuepress/config.js, docs/faq/README.md, docs/plugins/README.md
=> Add FAQ section

docs/01-installing.md, docs/03-lv-config.md, docs/README.md, docs/configuration/README.md, docs/configuration/colorschemes.md, docs/configuration/dap.md, docs/configuration/migrating.md, docs/plugins/README.md, docs/plugins/extending-configuration-for-core-plugins.md, docs/plugins/plugin-quickstart.md
Rename lv-config.lua to config.lua
=> rename lv-config.lua to config.lua

docs/faq/README.md
Update the keybindings' section in FAQ for rolling
=> update faq for rolling

docs/plugins/plugin-quickstart.md
Following [the discussion](https://github.com/ChristianChiarulli/LunarVim/issues/616#issuecomment-890879802) on PR #616 now that the wiki has moved to lunarvim.org.
The is a request to fix the lastplace module and to add comments to each of the modules so that they are "plug and play".
=> fixing lastplace module and adding commenting at the end of each module

docs/configuration/keybindings.md
I was getting `keymappings.lua:41: Expected lua table`. I don't know lua so please check.
=> Use lua table for normal_mode keys example

README.md
Handy url to website and url when running locally
=> add urls to local and website

docs/plugins/plugin-quickstart.md
vim-repeat lazy loading make the first . not working.
=> vim-repeat lazy loading doesn't work

docs/languages/python.md
=> Debugging instructions for python

docs/languages/README.md
Add missing period/capitalization.
=> Add missing period/capitalization.

docs/.vuepress/config.js
fixes the repo name in the vuepress config file
=> [Fix] fix repo name

docs/languages/powershell.md
=> [Docs] Add PowerShell

docs/languages/csharp.md
=> [Docs] Add C# (csharp) to languages

docs/languages/README.md
Add info about required manual installation of formatters and linters.
=> [Refactor] Mention formatter and linter installation

docs/languages/javascript.md
Mention react formatter and linter configuration. Refer to TypeScript page for LSP installation and configuration.
=> [Refactor] Add react formatter and linter config. Refer to TypeScript page for LSP.

docs/plugins/02-extra-plugins.md
Add missing links to github repos in the extra-plugins page, with some plugins descriptions
=> Add extra-plugin links and descriptions

docs/languages/c_cpp.md
Not 100% sure of the content as I do not code C/C++, but it is a start.
=> [Docs] Add C/C++ languages

docs/configuration/02-keybindings.md
I am not sure if people understand that ["TP"] means adding "Project" to the "Telescope" submenu.
=> How to add key to a existing submenu

docs/languages/go.md, docs/languages/json.md
Add `go`, `json` language configuration
=> Add go, json language configuration

docs/configuration/02-keybindings.md
=> clarify keybinding usage

docs/02-after-install.md
=> How to add lvim to path

docs/plugins/README.md
I ran into this and Hatsu and reisnobre (in Discord) helped me to solve it. I thought I'd add this to the documentation so others didn't run into the same issue.
=> Update plugin documentation

docs/plugins/README.md
This is per Hatsu's suggestion.
=> Use PackerSync instead of PackerCompile

docs/languages/go.md
=> update go debugger

docs/01-installing.md
Add link for resolving eaccess errors.  To installer trouble-shooting section.
=> add link for resolving eaccess errors

docs/01-installing.md
Closes:
https://github.com/LunarVim/LunarVim/issues/1528
and
https://github.com/LunarVim/lunarvim.org/issues/84
=> [#84] Add prerequisites and more toubleshooting to installing.md

docs/dev/README.md
why:
For me it was hard to understand how `lua` and `lvim` was setup properly for development. This might be confusing for some people. So though to shed some light on how to setup the development locally.
what:
docs on "getting started" with development of lunarvim
=> docs: setup local env

docs/languages/README.md
=> add description and example to formatter args

docs/01-installing.md
I'm a Chinese user of lunarvim. For some reason, it's really slow when we access github content, which leads to installation failure. So I add these tips for install lunarvim fast.
=> Add some installation tips for Chinese users.

docs/configuration/README.md, docs/plugins/02-default-plugins.md
Command to to generate an lv-settings.lua file updated as discussed in discord + fix for two dead plugin link
=> Fixes outdated command dead links

docs/languages/julia.md
Update instructions and add some other tips to get better overall experience most julia devs want.
=> chore: update juila docs

docs/drafts/enabling-a-language-server.md, docs/languages/README.md, docs/languages/javascript.md, docs/languages/julia.md, docs/languages/powershell.md, docs/languages/typescript.md
Hello! This document was recently moved so figured I'd update these links
=> doc: update nvim-lspconfig links

docs/plugins/03-extra-plugins.md
=> fix: replace tabnine-compe with cmp-tabnine

docs/languages/c_cpp.md
Took me forever to figure this out so I thought other people might find this useful haha
=> Add debug configuration example for C++ with ccppr_vsc

docs/.vuepress/config.js, package.json
For new people, searching through the page is not that fast, vuepress has a search function that works well.
I think that this can be help to attract potential users.
=> Adding local search

docs/languages/go.md
TS Parser not available for language gopls. It's go
=> change TSInstall gopls to go

docs/languages/csharp.md
`:LspInstall csharp` in no longer working, instead auto complete suggests `c#`
=> docs Fix csharp lsp install command

docs/.vuepress/config.js
Fixes broken links on the Troubleshooting page, mentioned in #77.
=> Fixes sidebar on the Troubleshooting page

.gitignore, package.json
Title pretty much says everything.
=> Bump deps, and add pnpm-lock.yaml to .gitignore

docs/languages/swift.md, package.json
Added docs for Swift language, and bump docs
Please provide comments for the docs created here.
Is the LSP setup too over-complicated? I took inspiration for the LSP setup from [abzcoding/lvim/ftplugin/python.lua](https://github.com/abzcoding/lvim/blob/main/ftplugin/python.lua)
=> Added docs for swift language

docs/01-installing.md
Added tips for WSL 2.
@kylo252  @abzcoding  Since you both help out a lot of `lvim` users, have you guys any other issues that should be added to the WSL 2 section?
Screenshot of what I have added below.
=> Added docs for WSL2 regarding clipboard and directories

docs/01-installing.md
Adds tip for WSL2 users regarding slow buffers.
Muse: @kylo252  in https://github.com/LunarVim/LunarVim/issues/2309
=> Added additional tip for wsl2 users

docs/plugins/02-extra-plugins.md
Add `nvim-treesitter-context` in the wiki. It may be useful for other people.
=> Add nvim-treesitter-context

docs/languages/README.md, docs/languages/go.md, docs/languages/python.md, docs/languages/rust.md, docs/languages/vue.md
=> fix(nslpsettings): use LspSettings instead of the deprecated NlspConfig

docs/plugins/02-extra-plugins.md
This is a problem that drove me nuts for some time. Not sure if the config function is the best place, but it is the most self-contained one
=> Update 02-extra-plugins.md to configure vim-surround

docs/languages/README.md
Thanks for this awesome library :)
=> [chore] Fix typo

docs/plugins/02-extra-plugins.md
Related to LunarVim/LunarVim#2426
=> Add instructions about how to register telescope extensions

docs/01-installing.md, docs/troubleshooting/README.md
Just to avoid any other issues regarding ansi colors etc.
=> Add prerequisite for terminal

docs/02-installation.md
=> easter egg

docs/02-installation.md, docs/languages/java.md, docs/languages/scala.md, docs/plugins/README.md, docs/troubleshooting/README.md
=> docs: fix-typos

docs/01-installation.md
Copy the update instructions from @LunarVim main repo to the install page.
=> docs: adds update instructions

docs/languages/java.md
https://docusaurus.io/docs/markdown-features/admonitions
=> Use Admonitions for notes

docs/02-quick-start.md, docs/configuration/01-settings.md, docs/configuration/02-keybindings.md, docs/configuration/04-nerd-fonts.md
embedding youtube videos from [chrismachine](https://www.youtube.com/c/ChrisAtMachine) in docs.
Fixes: https://github.com/LunarVim/lunarvim.org/issues/234
=> embed youtube video/videos/playlist to docs where appropriate

docs/configuration/02-keybindings.md
More docs are always nice to have :)
=> docs: removing a mapping via which-key

docs/frameworks/vue.md, docs/languages/c_cpp.md, docs/languages/csharp.md, docs/languages/go.md, docs/languages/hcl.md, docs/languages/java.md, docs/languages/javascript.md, docs/languages/json.md, docs/languages/lua.md, docs/languages/python.md, docs/languages/ruby.md, docs/languages/rust.md, docs/languages/scala.md, docs/languages/typescript.md, scripts/autogen_docs.sh, scripts/autogen_lsp_docs.lua, scripts/autogen_plugins_docs.lua, scripts/core_plugins.json
- ci: re-add language scripts
- fix: update language files
=> fix: update language files

docusaurus.config.js
change announcement content before merge
=> add announcements bar

docs/languages/java.md
Hey!
I recently started to use LunarVim in one of my projects. It took time to make formatting work as I wanted, and I learned many things the hard way. I would like to update java.md in a way that would have helped me from the beginning, and I hope it can help other newcomers.
=> Improve documentation in java.md

docusaurus.config.js
I added some tag lines, and fixed a typo
=> feat: add some more tag lines

i18n/es/docusaurus-plugin-content-docs/current/01-installation.md, i18n/es/docusaurus-plugin-content-docs/current/02-quick-start.md, i18n/es/docusaurus-plugin-content-docs/current/configuration/01-settings.md, i18n/es/docusaurus-plugin-content-docs/current/configuration/02-keybindings.md, i18n/es/docusaurus-plugin-content-docs/current/configuration/04-nerd-fonts.md, i18n/es/docusaurus-plugin-content-docs/current/configuration/07-ftplugin.md, i18n/es/docusaurus-plugin-content-docs/current/configuration/08-custom-snippets.md
Some of the commands of installation and videos have changed in the EN version, i have updated them and added the videos.
Also, the `configuration` section has been fully translated.
=> docs: Update ES installation commands and added ES translations.

docs/01-installation.md, versioned_docs/version-1.2/01-installation.md
=> docs(installation): update installation page for windows

.github/actions/spelling/allow.txt, .github/workflows/spelling.yml
there were missing words in allow.txt, my branch was behind
=> fix: mistakes in spell checking action

package.json, src/components/ChristmasAnimations/index.jsx, src/components/ChristmasAnimations/styles.module.css, src/components/Hero/index.jsx, src/pages/index.jsx, yarn.lock
try it locally before merge.
I think the animations is too much,
should we remove the snowfall and keep the lights rope? or vise versa?
=> Christmas update

versioned_docs/version-1.2/plugins/02-extra-plugins.md
adding the highlighting to the autocommand minimap
=> Update code highlighting

.github/actions/spelling/allow.txt, docs/01-installation.md
fixes an issue where powershell would exit if there are errors
=> docs(installation): don't exit powershell on error

.github/workflows/spelling.yml
=> ci(spell-checking): update to 0.0.21, pin dictionary version

src/components/MeetTheTeam/index.jsx, src/components/MeetTheTeam/styles.modules.css
=> feat(MeetTheTeam): better responsiveness

docs/configuration/02-keybindings.md, docs/plugins/README.md, docs/troubleshooting/README.md
waiting for https://github.com/LunarVim/LunarVim/pull/3647
PRs to merge together with this one: #327
=> refactor: packer -> lazy

docs/plugins/02-extra-plugins.md
Followed the Migration Guide here: https://github.com/folke/lazy.nvim#packernvim and did simple search/replace.
=> docs(extra-plugins): Update extra-plugins.md examples for lazy.nvim

.github/workflows/pr-yarn-build.yml
=> feat(ci): `yarn build` pr check

package.json, src/components/MeetTheTeam/index.jsx, src/components/MeetTheTeam/styles.modules.css, yarn.lock
I have improved the MeetTheTeam components by incorporating a loading placeholder for each member card, and by refactoring the code for improved readability. I am planning on further refining the code in the future.
=> refactor: improve MeetTheTeam

src/components/MeetTheTeam/index.jsx
I fixed the issue of inconsistent spacing when only a username is provided, and also made several stylistic improvements to enhance the readability of the mentioned components.
=> fix(MeetTheTeam): title name-username spacing

.github/actions/spelling/allow.txt, .stylua.toml, docs/configuration/language-features/language-servers.md, docs/configuration/language-features/linting-and-formatting.md
=> docs: improve lsp docs

docs/installation/installation.md, versioned_docs/version-1.2/installation.md
=> docs: fix docker install command

docs/configuration/plugins/core-plugins.md, docs/configuration/plugins/user-plugins.md
=> docs: improve plugins section

src/components/Hero/index.jsx, src/components/Hero/index.module.css
Add a simple description in the `Hero` Component to describe what LunarVim is.
fixes #362
=> feat: add project description to hero

i18n/es/docusaurus-plugin-content-blog/options.json, i18n/es/docusaurus-theme-classic/navbar.json
Add some translation for blog SEO and sidebar and theme navbar
@Nojipiz can you review the proposed changes?
=> Add further spanish translation

.github/actions/spelling/expect.txt, docs/configuration/appearance/colorschemes.md
docs(colorscheme): Add example on how to override builtin parameters
=> docs(colorscheme): Add example on how to override builtin parameters

docs/installation/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation/installation.md
=> docs(zh-Hans & en): fix typo for installation.md

docusaurus.config.js, package.json, src/components/YouTube/index.jsx, src/components/YouTube/styles.module.css, src/components/YouTube/yt-lite.css, yarn.lock
[React Lite YouTube Embed](https://github.com/ibrahimcesar/react-lite-youtube-embed) will presents a minimal thumbnail and play button. Clicking the element dynamically loads the full YouTube embed code, meaning users who never click play don't pay the cost of fetching and processing it, this will save users some bandwidth and loads the landing page faster
=> feat(Landing Page): Use React Lite YouTube Embed instead of ifram for better performance

docs/beginners-guide/plugins-overview.md
=> docs: NERDTree to NvimTree

docs/installation/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.3/installation/installation.md
Add curl in the try command for the docs, as it is needed to run the installer
=> Install curl in the "try" command as it is needed to run the installer

docs/installation/post-install.md
getnf has moved to its own org, updated the link to it.
=> Updated getnf location

docs/troubleshooting/README.md, versioned_docs/version-1.3/troubleshooting/README.md
Hello, in this issue I try to solve an error that I got, when installing neovim using bob (neovim package manager), this bug was shown how to solve in [issue #3612](https://github.com/LunarVim/LunarVim/issues/3612), and I think it would be nice to have that info in troubleshooting section.
=> Add troubleshooting lvim, with neovim installed with bob
